spring.application.name=msidentity
server.port=${SERVER_PORT:8080}

# DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/msidentity_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:msidentity_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:msidentity_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin_pass}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
